version: "3.8"

services:
  postgres:
    image: postgres:13.3
    user: root
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data_pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    user: root
    restart: always
    ports:
      - 5051:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: correct
    volumes:
      - ./data_admin:/var/lib/pgadmin